# Generated by Django 4.2.2 on 2023-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_long',
            field=models.CharField(default='long description tmp tmp tmp', max_length=2048, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=1028, unique=True),
        ),
    ]
